services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - database
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@database:5432/mydb"

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app

  database:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
